# Generated by Django 4.2.1 on 2023-06-05 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_price_changed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='price',
            new_name='cost_price',
        ),
        migrations.AddField(
            model_name='recipe',
            name='final_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
